<a href="https://colab.research.google.com/github/freetech357/flaskapi/blob/main/chapter_appendix-tools-for-deep-learning/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import numpy as np
from numpy import array as arr

a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [85]:
b = a.reshape(3,2)
b.shape

(3, 2)

In [86]:
a[a < 5]

array([1, 2, 3, 4])

In [87]:
five_up = (a >= 5)
five_up

array([False, False, False, False,  True,  True])

In [88]:
a[five_up]

array([5, 6])

In [89]:
a[a%2 == 0]

array([2, 4, 6])

In [90]:
con = (a%2 == 0)
con

array([False,  True, False,  True, False,  True])

In [91]:
a[con]

array([2, 4, 6])

In [93]:
five_or = (a > 5) | (a == 5)
a[five_or]

array([5, 6])

In [95]:
five_and = (a > 4) & (a < 6)
a[five_and]

array([5])

# **Numpy Non-Zero**

In [100]:
nonzero = np.nonzero(a == 10)
nonzero

(array([], dtype=int64),)